insert into client_addresses (address_id, city, street_address, postal_code, description) values (1, 'Bielawa', 'Balwierska', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (2, 'Olszyna', 'Słoneczna Polana', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (3, 'Karpacz', 'Adama', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (4, 'Świerzawa', 'Karola', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (5, 'Kąty Wrocławskie', 'Trzebnicka', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (6, 'Twardogóra', 'Cisawa', '01-234', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (7, 'Nowa Ruda', 'Mickiewicza', '34-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (8, 'Żarów', 'Zielona', '89-076', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (9, 'Strzelin', 'Wierzbowa', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (10, 'Żmigród', 'Świerkowa', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (11, 'Syców', 'Łomnicka', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (12, 'Ząbkowice Śląskie', 'Rybacka', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (13, 'Wałbrzych', 'Cicha', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (14, 'Chocianów', 'Spacerowa', '34-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (15, 'Szczytna', 'Adama', '28-653', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (16, 'Jedlina-Zdrój', 'Łomnicka', '89-076', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (17, 'Prochowice', 'Świerkowa', '54-876', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (18, 'Ziębice', 'Polna', '89-076', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (19, 'Gryfów Śląski', 'Wierzbowa', '01-234', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (20, 'Wołów', 'Granitowa', '54-876', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (21, 'Lubomierz', 'Agrestowa', '54-876', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (22, 'Mieroszów', 'Handlowa', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (23, 'Pieńsk', 'Kolejowa', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (24, 'Międzylesie', 'Bławatna', '89-076', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (25, 'Kowary', 'Kopernika', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (26, 'Bogatynia', 'Chmielna', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (27, 'Bogatynia', 'Kolejowa', '28-653', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (28, 'Olszyna', 'Radarowa', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (29, 'Mirsk', 'Świerkowa', '89-076', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (30, 'Ziębice', 'Maja', '01-234', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (31, 'Bogatynia', 'Kolejowa', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (32, 'Węgliniec', 'Mickiewicza', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (33, 'Wołów', 'Kolejowa', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (34, 'Kamienna Góra', 'Magnoliowa', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (35, 'Boguszów-Gorce', 'Modrzewiowa', '54-876', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (36, 'Bielawa', 'Kraszewskiego', '54-876', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (37, 'Legnica', 'Poprzeczna', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (38, 'Pieszyce', 'Poprzeczna', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (39, 'Złoty Stok', 'Jesionowa', '34-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (40, 'Niemcza', 'Wielkopolska', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (41, 'Złotoryja', 'Batalionów Chłopskich', '01-234', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (42, 'Wrocław', 'Słowicza', '01-234', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (43, 'Kąty Wrocławskie', 'Modrzewiowa', '28-653', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (44, 'Prusice', 'Grabowa', '01-234', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (45, 'Wleń', 'Magnoliowa', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (46, 'Brzeg Dolny', 'Topolowa', '89-076', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (47, 'Wleń', 'Wrocławska', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (48, 'Wojcieszów', 'Kamienna', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (49, 'Ziębice', 'Adama', '34-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (50, 'Prusice', 'Jaśminowa', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (51, 'Bolków', 'Cicha', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (52, 'Ziębice', 'Kolejowa', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (53, 'Świeradów-Zdrój', 'Dębowa', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (54, 'Bardo', 'Dębowa', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (55, 'Karpacz', 'Świerkowa', '54-876', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (56, 'Przemków', 'Batalionów Chłopskich', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (57, 'Lubawka', 'Spacerowa', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (58, 'Duszniki-Zdrój', 'Wiejska', '34-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (59, 'Ścinawa', 'Cicha', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (60, 'Szczytna', 'Perseusza', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (61, 'Oleśnica', 'Wiosenna', '01-234', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (62, 'Lubin', 'Rybacka', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (63, 'Międzylesie', 'Kolejowa', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (64, 'Bardo', 'Topolowa', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (65, 'Węgliniec', 'Cicha', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (66, 'Szczawno-Zdrój', 'Cicha', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (67, 'Kudowa-Zdrój', 'Cicha', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (68, 'Bierutów', 'Cicha', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (69, 'Jelenia Góra', 'Spacerowa', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (70, 'Wrocław', 'Stanisława', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (71, 'Przemków', 'Szymanowskiego', '34-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (72, 'Piława Górna', 'Brzozowa', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (73, 'Oleśnica', 'Dzika', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (74, 'Złoty Stok', 'Groszowiecka', '34-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (75, 'Pieszyce', 'Bzowa', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (76, 'Mieroszów', 'Józefa', '34-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (77, 'Legnica', 'Kolejowa', '01-234', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (78, 'Mieroszów', 'Adama', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (79, 'Brzeg Dolny', 'Cicha', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (80, 'Świdnica', 'Staromłyńska', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (81, 'Głogów', 'Obrońców Pokoju', '28-653', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (82, 'Złotoryja', 'Dworska', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (83, 'Lądek-Zdrój', 'Strażacka', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (84, 'Polkowice', 'Dębowa', '28-653', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (85, 'Szczawno-Zdrój', 'Wierzbowa', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (86, 'Oleśnica', 'Wyspiańskiego', '01-234', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (87, 'Wałbrzych', 'Przechodnia', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (88, 'Głuszyca', 'Cisowa', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (89, 'Pieszyce', 'Obrońców Pokoju', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (90, 'Kłodzko', 'Cytrynowa', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (91, 'Lubań', 'Zielona', '01-234', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (92, 'Bolków', 'Maja', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (93, 'Prochowice', 'Asnyka', '54-876', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (94, 'Głuszyca', 'Rogowa', '28-653', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (95, 'Lubomierz', 'Herbsta', '28-653', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (96, 'Pieńsk', 'Radarowa', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (97, 'Ziębice', 'Miła', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (98, 'Szczawno-Zdrój', 'Agrestowa', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (99, 'Nowa Ruda', 'Skowronkowa', '54-876', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (100, 'Jelenia Góra', 'Kościelna', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (101, 'Kamienna Góra', 'Polna', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (102, 'Boguszów-Gorce', 'Wiejska', '54-876', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (103, 'Wrocław', 'Modrzewiowa', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (104, 'Zawidów', 'Agrestowa', '34-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (105, 'Zgorzelec', 'Leszczynowa', '28-653', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (106, 'Bolków', 'Piaskowa', '28-653', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (107, 'Piława Górna', 'Obrońców Pokoju', '34-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (108, 'Zgorzelec', 'Kamienna', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (109, 'Szklarska Poręba', 'Adama', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (110, 'Twardogóra', 'Wrocławska', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (111, 'Strzegom', 'Cisowa', '28-653', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (112, 'Ząbkowice Śląskie', 'Wiejska', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (113, 'Góra', 'Handlowa', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (114, 'Piechowice', 'Ignacego', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (115, 'Oborniki Śląskie', 'Brzozowa', '34-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (116, 'Szczytna', 'Jesienna', '34-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (117, 'Bogatynia', 'Magnoliowa', '34-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (118, 'Lwówek Śląski', 'Przechodnia', '01-234', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (119, 'Kamienna Góra', 'Zygmunta', '34-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (120, 'Zgorzelec', 'Mickiewicza', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (121, 'Mirsk', 'Polna', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (122, 'Kowary', 'Zielona', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (123, 'Bolków', 'Bławatna', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (124, 'Pieńsk', 'Malinowa', '28-653', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (125, 'Kudowa-Zdrój', 'Energetyczna', '54-876', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (126, 'Syców', 'Jesionowa', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (127, 'Mirsk', 'Karola', '01-234', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (128, 'Lubin', 'Rybacka', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (129, 'Węgliniec', 'Świerkowa', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (130, 'Boguszów-Gorce', 'Topolowa', '28-653', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (131, 'Świdnica', 'Wiejska', '34-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (132, 'Świeradów-Zdrój', 'Dworska', '89-076', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (133, 'Bardo', 'Spacerowa', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (134, 'Wołów', 'Augusta', '01-234', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (135, 'Piechowice', 'Obrońców Pokoju', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (136, 'Lubań', 'Spokojna', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (137, 'Chojnów', 'Krasińskiego', '54-876', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (138, 'Złotoryja', 'Złota', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (139, 'Pieńsk', 'Adama', '89-076', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (140, 'Zgorzelec', 'Zagajnik', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (141, 'Brzeg Dolny', 'Cicha', '54-876', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (142, 'Strzegom', 'Staromłyńska', '34-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (143, 'Środa Śląska', 'Wierzbowa', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (144, 'Lubin', 'Wrocławska', '28-653', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (145, 'Bogatynia', 'Wałowa', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (146, 'Wołów', 'Handlowa', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (147, 'Przemków', 'Kościelna', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (148, 'Głuszyca', 'Spacerowa', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (149, 'Kamienna Góra', 'Adama', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (150, 'Jelenia Góra', 'Magnoliowa', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (151, 'Jawor', 'Zielona', '54-876', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (152, 'Karpacz', 'Kamienna', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (153, 'Świeradów-Zdrój', 'Wrocławska', '89-076', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (154, 'Złoty Stok', 'Paprotna', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (155, 'Chocianów', 'Adama', '89-076', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (156, 'Lwówek Śląski', 'Krzycka', '54-876', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (157, 'Milicz', 'Spacerowa', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (158, 'Milicz', 'Krasińskiego', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (159, 'Gryfów Śląski', 'Maja', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (160, 'Lubawka', 'Cicha', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (161, 'Kąty Wrocławskie', 'Miła', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (162, 'Dzierżoniów', 'Piekarska', '89-076', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (163, 'Ścinawa', 'Cicha', '28-653', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (164, 'Syców', 'Cisowa', '01-234', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (165, 'Pieńsk', 'Balwierska', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (166, 'Lądek-Zdrój', 'Dobra', '50-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (167, 'Kowary', 'Dziadoszan', '54-876', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (168, 'Bierutów', 'Suchowicka', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (169, 'Oleśnica', 'Słowicza', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (170, 'Piława Górna', 'Wiejska', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (171, 'Nowogrodziec', 'Józefa', '01-234', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (172, 'Świdnica', 'Mickiewicza', '28-653', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (173, 'Bystrzyca Kłodzka', 'Polna', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (174, 'Szczawno-Zdrój', 'Wiosenna', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (175, 'Szczytna', 'Jaśminowa', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (176, 'Leśna', 'Obrońców Pokoju', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (177, 'Jawor', 'Suchowicka', '28-653', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (178, 'Wąsosz', 'Magistracka', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (179, 'Ścinawa', 'Modrzewiowa', '54-876', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (180, 'Bierutów', 'Poprzeczna', '89-076', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (181, 'Gryfów Śląski', 'Bławatna', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (182, 'Ziębice', 'Polna', '34-123', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (183, 'Bolków', 'Malinowa', '28-653', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (184, 'Oborniki Śląskie', 'Bławatna', '34-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (185, 'Bolesławiec', 'Brzozowa', '01-234', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (186, 'Złoty Stok', 'Mickiewicza', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (187, 'Ząbkowice Śląskie', 'Polna', '89-076', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (188, 'Polanica-Zdrój', 'Jesienna', '01-234', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (189, 'Bogatynia', 'Świerkowa', '01-234', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (190, 'Bolków', 'Jeszkowicka', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (191, 'Ząbkowice Śląskie', 'Jaśminowa', '01-234', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (192, 'Mirsk', 'Maja', '54-876', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (193, 'Chojnów', 'Polna', '89-076', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (194, 'Chojnów', 'Maja', '89-076', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (195, 'Lubomierz', 'Wita', '34-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (196, 'Sobótka', 'Krasińskiego', '50-123', 'budowa');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (197, 'Strzegom', 'Cisawa', '28-653', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (198, 'Syców', 'Malinowa', '50-123', 'magazyn');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (199, 'Prochowice', 'Świerkowa', '01-234', 'zaplecze');
insert into client_addresses (address_id, city, street_address, postal_code, description) values (200, 'Jaworzyna Śląska', 'Dworska', '34-123', 'zaplecze');
