insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (1, 80, 4, 'Bogatynia', '', '63-600');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (2, 108, 4, 'Wojcieszów', 'Wałowa', '99-414');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (3, 104, 7, 'Zawidów', 'Zielona', '06-836');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (4, 137, 2, 'Siechnice', 'Batalionów Chłopskich', '63-600');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (5, 173, 1, 'Świdnica', 'Ignacego', '95-810');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (6, 108, 8, 'Strzelin', 'Wita', '62-239');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (7, 74, 12, 'Świerzawa', 'Świerkowa', '23-640');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (8, 128, 8, 'Złotoryja', 'Batalionów Chłopskich', '74-801');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (9, 117, 6, 'Chocianów', 'Cicha', '58-998');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (10, 142, 4, 'Zawidów', 'Dobra', '15-092');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (11, 163, 1, 'Prusice', 'Kolejowa', '43-209');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (12, 144, 7, 'Węgliniec', 'Żarkowska', '06-836');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (13, 112, 9, 'Oława', 'Kolejowa', '51-926');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (14, 99, 7, 'Siechnice', 'Kolejowa', '47-425');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (15, 172, 9, 'Szczawno-Zdrój', 'Cicha', '64-703');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (16, 99, 12, 'Kąty Wrocławskie', 'Ignacego', '11-049');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (17, 94, 13, 'Jelcz-Laskowice', 'Piekarska', '26-143');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (18, 104, 5, 'Środa Śląska', 'Perseusza', '64-472');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (19, 60, 2, 'Jelenia Góra', 'Cicha', '06-910');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (20, 50, 9, 'Jelcz-Laskowice', 'Batalionów Chłopskich', '68-231');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (21, 103, 5, 'Sobótka', 'Amarantowa', '01-721');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (22, 183, 1, 'Głuszyca', 'Królewska', '01-721');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (23, 55, 8, 'Przemków', 'Świerkowa', '19-639');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (24, 158, 10, 'Głuszyca', 'Letnia', '78-443');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (25, 123, 11, 'Zgorzelec', 'Zielona', '05-867');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (26, 65, 3, 'Świebodzice', 'Dziadoszan', '81-875');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (27, 114, 3, 'Przemków', 'Wiejska', '14-786');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (28, 61, 2, 'Zawidów', 'Szymanowskiego', '81-558');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (29, 94, 12, 'Polkowice', 'Świerkowa', '62-239');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (30, 164, 9, 'Chocianów', '', '23-104');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (31, 189, 2, 'Żarów', 'Karola', '54-932');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (32, 59, 7, 'Węgliniec', 'Dobra', '89-690');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (33, 84, 11, 'Zgorzelec', 'Cicha', '33-148');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (34, 53, 13, 'Bogatynia', 'Perseusza', '21-878');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (35, 131, 7, 'Złotoryja', 'Wiejska', '81-875');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (36, 61, 12, 'Brzeg Dolny', 'Dobra', '81-183');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (37, 147, 2, 'Prusice', 'Obrońców Pokoju', '55-746');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (38, 179, 10, 'Żarów', 'Cisawa', '22-168');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (39, 200, 1, 'Żmigród', 'Zielona', '05-305');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (40, 169, 7, 'Bogatynia', 'Kolejowa', '99-414');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (41, 118, 8, 'Ząbkowice Śląskie', 'Kolejowa', '52-094');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (42, 90, 11, 'Oborniki Śląskie', 'Kolejowa', '17-338');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (43, 152, 2, 'Środa Śląska', 'Maja', '39-176');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (44, 157, 10, 'Ziębice', 'Dziadoszan', '13-842');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (45, 78, 10, 'Wojcieszów', 'Ignacego', '63-600');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (46, 162, 4, 'Zawidów', 'Cicha', '43-209');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (47, 183, 11, 'Kąty Wrocławskie', 'Świerkowa', '52-104');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (48, 152, 13, 'Złoty Stok', 'Tenisowa', '28-249');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (49, 126, 6, 'Pieńsk', 'Ignacego', '77-370');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (50, 198, 1, 'Ziębice', 'Topolowa', '19-639');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (51, 68, 11, 'Żmigród', 'Perseusza', '13-842');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (52, 134, 4, 'Jelenia Góra', 'Zielona', '01-721');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (53, 82, 12, 'Sobótka', 'Cisawa', '74-395');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (54, 188, 5, 'Kąty Wrocławskie', 'Świerkowa', '97-425');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (55, 83, 5, 'Strzegom', 'Stwosza', '22-144');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (56, 199, 9, 'Boguszów-Gorce', 'Topolowa', '43-531');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (57, 179, 7, 'Zgorzelec', 'Zielona', '80-106');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (58, 127, 12, 'Świdnica', 'Kolejowa', '23-640');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (59, 73, 8, 'Zgorzelec', 'Obrońców Pokoju', '39-757');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (60, 172, 3, 'Boguszów-Gorce', 'Topolowa', '43-209');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (61, 140, 4, 'Trzebnica', 'Letnia', '61-140');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (62, 150, 6, 'Wołów', 'Karola', '61-140');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (63, 126, 10, 'Zgorzelec', 'Świerkowa', '07-684');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (64, 63, 10, 'Ziębice', '', '57-942');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (65, 153, 2, 'Złoty Stok', 'Dobra', '12-593');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (66, 193, 11, 'Siechnice', 'Wiejska', '26-080');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (67, 122, 1, 'Żarów', 'Cytrynowa', '51-926');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (68, 200, 1, 'Jelcz-Laskowice', 'Ignacego', '80-648');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (69, 59, 4, 'Żmigród', 'Świerkowa', '53-866');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (70, 164, 6, 'Strzelin', 'Dobra', '33-524');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (71, 193, 6, 'Bogatynia', 'Ślusarska', '22-168');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (72, 197, 6, 'Sobótka', 'Wiejska', '52-956');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (73, 113, 13, 'Kąty Wrocławskie', 'Kolejowa', '01-721');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (74, 168, 8, 'Sobótka', 'Jesienna', '97-425');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (75, 191, 5, 'Jelcz-Laskowice', 'Cisawa', '43-986');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (76, 81, 4, 'Bardo', 'Maja', '13-094');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (77, 176, 6, 'Środa Śląska', 'Świerkowa', '72-779');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (78, 197, 1, 'Kąty Wrocławskie', 'Wita', '64-472');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (79, 53, 8, 'Węgliniec', 'Obrońców Pokoju', '05-305');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (80, 199, 11, 'Żmigród', 'Królewska', '53-292');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (81, 56, 5, 'Strzegom', 'Stwosza', '97-645');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (82, 177, 3, 'Sobótka', 'Kolejowa', '58-127');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (83, 101, 10, 'Ziębice', '', '80-106');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (84, 130, 7, 'Szczawno-Zdrój', 'Jesienna', '99-414');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (85, 104, 13, 'Wojcieszów', 'Letnia', '60-784');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (86, 62, 3, 'Jedlina-Zdrój', 'Stwosza', '81-183');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (87, 133, 9, 'Węgliniec', 'Zielona', '43-531');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (88, 123, 2, 'Kąty Wrocławskie', 'Biała', '77-370');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (89, 112, 3, 'Zawidów', 'Dziadoszan', '22-144');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (90, 111, 4, 'Strzegom', 'Stwosza', '06-910');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (91, 98, 7, 'Mieroszów', 'Biała', '01-721');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (92, 141, 10, 'Ziębice', 'Jesienna', '81-875');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (93, 94, 11, 'Kąty Wrocławskie', 'Zielona', '43-986');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (94, 142, 12, 'Świdnica', 'Kolejowa', '22-985');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (95, 123, 4, 'Wojcieszów', 'Królewska', '23-640');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (96, 146, 6, 'Ziębice', 'Perseusza', '77-370');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (97, 55, 9, 'Mieroszów', 'Ślusarska', '51-926');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (98, 65, 8, 'Strzegom', 'Balwierska', '94-957');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (99, 151, 3, 'Oława', 'Tenisowa', '01-721');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (100, 69, 1, 'Strzegom', 'Stwosza', '39-757');
