insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (1, 107, 1, 'Bogatynia', '', '21-878');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (2, 176, 2, 'Środa Śląska', 'Ignacego', '99-414');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (3, 93, 3, 'Żarów', 'Zielona', '78-443');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (4, 172, 4, 'Żmigród', 'Jesienna', '04-695');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (5, 101, 5, 'Strzegom', 'Cicha', '97-096');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (6, 98, 6, 'Oława', 'Cisawa', '51-926');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (7, 125, 7, 'Przemków', 'Perseusza', '23-640');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (8, 79, 8, 'Polkowice', 'Letnia', '13-094');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (9, 61, 9, 'Zgorzelec', 'Paderewskiego', '39-176');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (10, 79, 10, 'Szczawno-Zdrój', 'Wita', '70-331');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (11, 164, 11, 'Jelenia Góra', 'Ignacego', '21-878');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (12, 187, 12, 'Strzelin', 'Topolowa', '77-370');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (13, 173, 13, 'Ząbkowice Śląskie', 'Obrońców Pokoju', '44-301');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (14, 107, 14, 'Złoty Stok', '', '33-148');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (15, 127, 15, 'Zawidów', 'Biała', '01-721');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (16, 147, 16, 'Jelcz-Laskowice', 'Zielona', '62-239');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (17, 146, 17, 'Żarów', 'Piekarska', '53-866');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (18, 95, 18, 'Przemków', 'Obrońców Pokoju', '52-094');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (19, 92, 19, 'Przemków', 'Tenisowa', '80-106');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (20, 78, 20, 'Węgliniec', 'Letnia', '63-600');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (21, 114, 21, 'Ząbkowice Śląskie', 'Ślusarska', '68-231');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (22, 59, 22, 'Pieńsk', 'Żarkowska', '52-104');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (23, 190, 23, 'Środa Śląska', 'Obrońców Pokoju', '07-684');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (24, 166, 24, 'Przemków', 'Wiejska', '60-784');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (25, 104, 25, 'Środa Śląska', 'Piekarska', '12-145');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (26, 94, 26, 'Głuszyca', 'Zielona', '74-801');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (27, 104, 27, 'Kąty Wrocławskie', 'Cicha', '12-791');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (28, 126, 28, 'Wiązów', 'Wiejska', '81-183');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (29, 178, 29, 'Złoty Stok', 'Obrońców Pokoju', '81-183');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (30, 54, 30, 'Kąty Wrocławskie', 'Amarantowa', '92-033');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (31, 101, 31, 'Sobótka', 'Wita', '62-239');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (32, 57, 32, 'Szczawno-Zdrój', 'Topolowa', '88-884');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (33, 70, 33, 'Zawidów', 'Letnia', '23-989');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (34, 96, 34, 'Bogatynia', 'Dobra', '61-140');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (35, 61, 35, 'Węgliniec', 'Ignacego', '60-784');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (36, 66, 36, 'Pieńsk', 'Tenisowa', '64-716');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (37, 93, 37, 'Węgliniec', 'Letnia', '06-836');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (38, 97, 38, 'Boguszów-Gorce', 'Cicha', '80-648');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (39, 116, 39, 'Wiązów', 'Kolejowa', '51-926');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (40, 90, 40, 'Prusice', 'Bursztynowa', '43-209');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (41, 181, 41, 'Sobótka', 'Biała', '43-986');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (42, 150, 42, 'Siechnice', 'Zielona', '47-425');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (43, 128, 43, 'Jedlina-Zdrój', 'Topolowa', '24-859');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (44, 174, 44, 'Jelenia Góra', 'Poczdamska', '13-842');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (45, 169, 45, 'Złoty Stok', 'Maja', '68-231');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (46, 146, 46, 'Siechnice', 'Perseusza', '33-148');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (47, 154, 47, 'Ziębice', 'Świerkowa', '78-443');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (48, 130, 48, 'Zgorzelec', 'Ignacego', '05-867');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (49, 180, 49, 'Strzelin', 'Kolejowa', '29-446');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (50, 197, 50, 'Chocianów', 'Poczdamska', '64-703');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (51, 176, 51, 'Szczawno-Zdrój', 'Cicha', '70-331');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (52, 165, 52, 'Środa Śląska', 'Stwosza', '92-033');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (53, 196, 53, 'Zawidów', 'Jesienna', '81-183');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (54, 51, 54, 'Zgorzelec', 'Zielona', '74-588');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (55, 136, 55, 'Wojcieszów', 'Królewska', '33-524');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (56, 123, 56, 'Złoty Stok', 'Maja', '51-926');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (57, 122, 57, 'Złoty Stok', 'Cytrynowa', '43-531');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (58, 116, 58, 'Strzegom', 'Poczdamska', '58-998');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (59, 191, 59, 'Sobótka', 'Perseusza', '73-749');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (60, 69, 60, 'Polkowice', 'Karola', '23-931');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (61, 63, 61, 'Złoty Stok', 'Wita', '05-867');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (62, 80, 62, 'Wiązów', 'Paderewskiego', '24-859');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (63, 196, 63, 'Szczawno-Zdrój', 'Biała', '85-087');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (64, 56, 64, 'Głuszyca', 'Zielona', '53-292');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (65, 61, 65, 'Mieroszów', 'Obrońców Pokoju', '40-045');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (66, 193, 66, 'Kąty Wrocławskie', 'Kolejowa', '66-696');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (67, 122, 67, 'Złotoryja', 'Kolejowa', '40-045');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (68, 189, 68, 'Głuszyca', 'Wiejska', '77-370');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (69, 153, 69, 'Mieroszów', 'Balwierska', '05-867');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (70, 96, 70, 'Trzebnica', 'Królewska', '47-425');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (71, 110, 71, 'Żarów', 'Wałowa', '23-931');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (72, 85, 72, 'Wiązów', 'Kolejowa', '79-662');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (73, 200, 73, 'Przemków', 'Poczdamska', '02-952');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (74, 178, 74, 'Żmigród', 'Tenisowa', '52-956');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (75, 61, 75, 'Świebodzice', 'Kolejowa', '07-684');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (76, 76, 76, 'Kąty Wrocławskie', 'Świerkowa', '73-749');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (77, 95, 77, 'Węgliniec', 'Letnia', '58-998');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (78, 160, 78, 'Bardo', 'Kolejowa', '21-878');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (79, 74, 79, 'Siechnice', 'Cicha', '76-542');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (80, 60, 80, 'Boguszów-Gorce', 'Topolowa', '06-910');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (81, 102, 81, 'Żarów', 'Cytrynowa', '59-332');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (82, 55, 82, 'Sobótka', 'Amarantowa', '70-331');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (83, 181, 83, 'Złoty Stok', 'Paderewskiego', '66-696');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (84, 138, 84, 'Zgorzelec', 'Karola', '26-080');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (85, 99, 85, 'Żarów', 'Tenisowa', '64-472');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (86, 191, 86, 'Bardo', 'Amarantowa', '76-463');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (87, 120, 87, 'Mieroszów', 'Świerkowa', '76-463');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (88, 160, 88, 'Boguszów-Gorce', 'Jesienna', '05-305');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (89, 184, 89, 'Siechnice', 'Topolowa', '28-249');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (90, 195, 90, 'Węgliniec', 'Karola', '12-791');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (91, 185, 91, 'Świerzawa', 'Batalionów Chłopskich', '51-926');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (92, 110, 92, 'Bardo', 'Stwosza', '53-719');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (93, 179, 93, 'Polkowice', 'Balwierska', '43-209');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (94, 136, 94, 'Brzeg Dolny', 'Jesienna', '11-049');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (95, 67, 95, 'Wojcieszów', 'Bursztynowa', '57-966');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (96, 126, 96, 'Szczawno-Zdrój', 'Szymanowskiego', '73-749');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (97, 154, 97, 'Złoty Stok', 'Biała', '64-716');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (98, 79, 98, 'Trzebnica', 'Tenisowa', '03-308');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (99, 118, 99, 'Zawidów', 'Żarkowska', '88-884');
insert into shops (shop_id, surface, warehouse_id, city, street_address, postal_code) values (100, 115, 100, 'Bardo', 'Wiejska', '97-425');
